### ISSUE TITLE
Can't send view_item, add_to_cart... etc ecommerce event.

### ISSUE THREAD

**Issue by akzone** [MauricioRobayo/nextjs-google-analytics#379]
Hello is this package only works for basic event like page_view, scroll?

I tried to send ecommerce event but it's not working.

https://developers.google.com/analytics/devguides/collection/ga4/ecommerce

Thank you.

**Comment by mike-niemand** [comment]
event("purchase", {
            transaction_id: 1,
            value: 99.99,
            currency: "USD",
            items: [] <--- array of items here
        });

**Comment by akzone** [comment]
Yes I did but the event doesn't sent.

> event("purchase", { transaction_id: 1, value: 99.99, currency: "USD", items: [] <--- array of items here });

**Comment by mike-niemand** [comment]
Definitely working for me through many 1000's of transactions.

**Comment by akzone** [comment]
Thanks for the help, finally figured out that must add this line to send event

.env file
NEXT_PUBLIC_GA_MEASUREMENT_ID=xxxxx THIS WORK

_app.js
<GoogleAnalytics gaMeasurementId="xxxxx" /> THIS WON'T WORK

**Comment by MauricioRobayo** [comment]
> .env file
> NEXT_PUBLIC_GA_MEASUREMENT_ID=xxxxx THIS WORK
>
> _app.js
> `<GoogleAnalytics gaMeasurementId="xxxxx" />` THIS WON'T WORK

@akzone thanks for reporting this!

I've been looking into it as this should not be the expected behavior but could not find anything that might be causing this.

Do you have a repo where this is reproducible?

I created a [test repo](https://github.com/MauricioRobayo/event-test/blob/main/src/pages/_app.tsx) and it seems to be working fine while using the `gaMeasurementId` prop, I'm using the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) chrome extension:

```ts
// _app.ts
import type { AppProps } from "next/app";
import { GoogleAnalytics } from "nextjs-google-analytics";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <GoogleAnalytics gaMeasurementId="xxxxxxx" />
      <Component {...pageProps} />
    </>
  );
}
```

<img width="717" alt="Screenshot 2023-02-27 at 9 34 43 AM" src="https://user-images.githubusercontent.com/2121481/221592134-701c02a2-6143-4f2e-a138-718602eeebac.png">

**Comment by MauricioRobayo** [comment]
ahhh, that might have been caused by the `event` requiring a `gaMeasurementId`, but that was recently removed:

https://github.com/MauricioRobayo/nextjs-google-analytics/pull/313

Would you mind updating to the latest version and testing it again?

**Comment by akzone** [comment]
> ahhh, that might have been caused by the `event` requiring a `gaMeasurementId`, but that was recently removed:
> 
> 
> 
> https://github.com/MauricioRobayo/nextjs-google-analytics/pull/313
> 
> 
> 
> Would you mind updating to the latest version and testing it again?

Tested, it's okay now!

Thanks for the great work!
